apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphasense-deployment
  namespace: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: alphasense-container
        image: myapp:2.0.1
        ports:
        - containerPort: 5000
        env:
        - name: CONFIG_PATH
          value: "/etc/myapp/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/myapp/"
          readOnly: true
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: myapp-config
          items:
          - key: config.yaml
            path: config.yaml
